repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - args:
    - --maxkb=2000
    id: check-added-large-files
  - id: detect-private-key
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-toml
  - id: sort-simple-yaml
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.33.0
- hooks:
  - id: optimize-png
  - id: optimize-jpg
  repo: https://github.com/boidolr/pre-commit-images
  rev: v1.0.7
